### ISSUE TITLE
crash when i try to use SpatialReference.ImportFromEPSG

### ISSUE THREAD

**Issue by sgueniot** [wshunli/gdal-android#1]
hello, 
i have a crash when i try to use ImportFromEPSG from a SpatialReference.
working python code : 
```from osgeo import osr
from osgeo import gdal
src = osr.SpatialReference()
tgt = osr.SpatialReference()
src.ImportFromEPSG(4326)
tgt.ImportFromEPSG(2154)
transform = osr.CoordinateTransformation(src, tgt)
easting=9.172643
northing= 42.577890
longitude, latitude, z = transform.TransformPoint(easting, northing)
print("Lambert93 = ",longitude,",",latitude )
 ```
not working java code : 
```      SpatialReference src = new SpatialReference();
        SpatialReference tgt = new SpatialReference();
        src.ImportFromEPSG(4326); // crash here
        tgt.ImportFromEPSG(2154);
        CoordinateTransformation transform =  new CoordinateTransformation(src,tgt);
        double easting = 9.172643;
        double northing = 42.577890;
        double[] result = transform.TransformPoint(easting, northing);
        Log.d("transform","Lambert93 ="+result[0]+","+result[1]);
 ```
crash log :
```
java.lang.RuntimeException: OGR Error: General Error
        at org.gdal.osr.osrJNI.SpatialReference_ImportFromEPSG(Native Method)
        at org.gdal.osr.SpatialReference.ImportFromEPSG(SpatialReference.java:561)
        at com.wshunli.gdal.android.demo.MainActivity.onCreate(MainActivity.java:35)
```
Does anyone have any ideas to fix this problem?
thanks.

**Comment by sgueniot** [comment]
I think the problem is related to the GDAL_DATA folder that is missing, and in particular the gcs.csv file inside. but I don't know how to add this in android.
https://trac.osgeo.org/gdal/browser/trunk/gdal/data/gcs.csv

Anyone ?
thanks !

**Comment by sgueniot** [comment]
it's ok, you need to set the environment variable GDAL_DATA with the path of the directory that contains all the csv needed by gdal
